groups:
- name: voenmeh_bot_alerts
  rules:
  - alert: HighErrorRate
    expr: increase(bot_errors_total{source=~"parser|weather|handler|tasks"}[5m]) > 20
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "bot_errors_total increased by more than 20 in the last 5 minutes."

  - alert: RetryStorm
    expr: increase(bot_retries_total{component=~"parser|weather|tasks"}[5m]) > 50
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Retries are surging"
      description: "bot_retries_total increased by more than 50 in the last 5 minutes."
