apiVersion: 1
deleteDatasources:
  - name: Prometheus
  - name: Loki
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        - datasourceUid: "Prometheus" # Связываем с Prometheus для корреляции логов и метрик
          matcherRegex: 'trace_id="(\w+)"'
          name: "TraceID"
          url: "$${__value.raw}"
