"""Create users table

Revision ID: 3f6d2d644caf
Revises:
Create Date: 2025-07-10 17:13:40.631347

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f6d2d644caf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("group", sa.String(), nullable=True),
        sa.Column("registration_date", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_active_date", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("evening_notify", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("morning_summary", sa.Boolean(), server_default="t", nullable=False),
        sa.Column("lesson_reminders", sa.Boolean(), server_default="t", nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
