"""Add morning and evening time to user

Revision ID: 6f43e6269297
Revises: '8a2512e1862a'
Create Date: 2026-02-12 15:14:18.862927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6f43e6269297'
down_revision: Union[str, None] = '8a2512e1862a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('semester_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('morning_time', sa.String(length=5), server_default='08:00', nullable=False))
    op.add_column('users', sa.Column('evening_time', sa.String(length=5), server_default='20:00', nullable=False))
    op.drop_index(op.f('ix_users_evening_notify'), table_name='users')
    op.drop_index(op.f('ix_users_group'), table_name='users')
    op.drop_index(op.f('ix_users_lesson_reminders'), table_name='users')
    op.drop_index(op.f('ix_users_morning_summary'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_morning_summary'), 'users', ['morning_summary'], unique=False)
    op.create_index(op.f('ix_users_lesson_reminders'), 'users', ['lesson_reminders'], unique=False)
    op.create_index(op.f('ix_users_group'), 'users', ['group'], unique=False)
    op.create_index(op.f('ix_users_evening_notify'), 'users', ['evening_notify'], unique=False)
    op.drop_column('users', 'evening_time')
    op.drop_column('users', 'morning_time')
    op.alter_column('semester_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
