"""Add indexes to users table

Revision ID: a1b2c3d4e5f6
Revises: 3f6d2d644caf
Create Date: 2025-07-29 12:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "3f6d2d644caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_group", "users", ["group"], unique=False)
    op.create_index("ix_users_evening_notify", "users", ["evening_notify"], unique=False)
    op.create_index("ix_users_morning_summary", "users", ["morning_summary"], unique=False)
    op.create_index("ix_users_lesson_reminders", "users", ["lesson_reminders"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_lesson_reminders", table_name="users")
    op.drop_index("ix_users_morning_summary", table_name="users")
    op.drop_index("ix_users_evening_notify", table_name="users")
    op.drop_index("ix_users_group", table_name="users")
    # ### end Alembic commands ###
